services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - sqlite_data:/app/data
    environment:
      NODE_ENV: production
    ports:
      - "7000:7000"
    networks:
      - caddy
    restart: always

networks:
  caddy:
    driver: bridge

volumes:
  sqlite_data:
